import argparse
import random
from dataclasses import dataclass


def _dedupe_keep_order(items: list[bytes]) -> list[bytes]:
    seen: set[bytes] = set()
    out: list[bytes] = []
    for x in items:
        if x in seen:
            continue
        seen.add(x)
        out.append(x)
    return out


def _generate_inputs(seed: int) -> list[bytes]:
    inputs: list[bytes] = []

    inputs += [
        b"",
        b"f",
        b"fo",
        b"foo",
        b"deadBEEF",
        b"Hello, World!",
        b"0123456789",
        b"01",
        b"01234567",
        b"012345678",
        b"abcdef",
        b"ABCDEF",
        b"abcDEF123",
        b"[]{}()<>",
        b" \t\n\r\v\f",
    ]

    singles = [
        0x00,
        0x01,
        0x08,
        0x09,
        0x0A,
        0x0B,
        0x0C,
        0x0D,
        0x1F,
        0x20,
        0x21,
        0x2F,
        0x30,
        0x31,
        0x37,
        0x38,
        0x39,
        0x3A,
        0x40,
        0x41,
        0x46,
        0x5A,
        0x5B,
        0x60,
        0x61,
        0x66,
        0x7A,
        0x7B,
        0x7E,
        0x7F,
        0x80,
        0xFF,
    ]
    inputs += [bytes([b]) for b in singles]

    inputs += [
        bytes(range(0x00, 0x80)),
        bytes(range(0x00, 0x100)),
        bytes(range(0xFF, -1, -1)),
        bytes([0x00, 0xFF]) * 32,
    ]

    rng = random.Random(seed)
    lengths = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 31, 32, 33, 63, 64]
    for n in lengths:
        inputs.append(bytes(rng.randrange(256) for _ in range(n)))

    for _ in range(40):
        n = rng.randrange(0, 65)
        inputs.append(bytes(rng.randrange(256) for _ in range(n)))

    return _dedupe_keep_order(inputs)


def _to_lower_byte(b: int) -> int:
    if 0x41 <= b <= 0x5A:
        return b - 0x41 + 0x61
    return b


def _to_upper_byte(b: int) -> int:
    if 0x61 <= b <= 0x7A:
        return b - 0x61 + 0x41
    return b


def _is_any(b: int) -> bool:
    return b <= 0x7F


def _is_digit(b: int) -> bool:
    return 0x30 <= b <= 0x39


def _is_bit(b: int) -> bool:
    return b == 0x30 or b == 0x31


def _is_octal_digit(b: int) -> bool:
    return 0x30 <= b <= 0x37


def _is_hex_digit(b: int) -> bool:
    return _is_digit(b) or (0x41 <= b <= 0x46) or (0x61 <= b <= 0x66)


def _is_lower(b: int) -> bool:
    return 0x61 <= b <= 0x7A


def _is_upper(b: int) -> bool:
    return 0x41 <= b <= 0x5A


def _is_alphabetic(b: int) -> bool:
    return _is_lower(b) or _is_upper(b)


def _is_alphanumeric(b: int) -> bool:
    return _is_alphabetic(b) or _is_digit(b)


def _is_punctuation(b: int) -> bool:
    return (0x21 <= b <= 0x2F) or (0x3A <= b <= 0x40) or (0x5B <= b <= 0x60) or (0x7B <= b <= 0x7E)


def _is_graphic(b: int) -> bool:
    return 0x21 <= b <= 0x7E


def _is_printing(b: int) -> bool:
    return 0x20 <= b <= 0x7E


def _is_horizontal_whitespace(b: int) -> bool:
    return b == 0x20 or b == 0x09


def _is_whitespace(b: int) -> bool:
    return b == 0x20 or b == 0x0C or b == 0x0A or b == 0x0D or b == 0x09 or b == 0x0B


def _is_control(b: int) -> bool:
    return (0x00 <= b <= 0x1F) or b == 0x7F


@dataclass(frozen=True)
class Predicate:
    name: str
    fn: object


_PREDICATES = [
    Predicate("any", _is_any),
    Predicate("digit", _is_digit),
    Predicate("bit", _is_bit),
    Predicate("octal_digit", _is_octal_digit),
    Predicate("hex_digit", _is_hex_digit),
    Predicate("lower", _is_lower),
    Predicate("upper", _is_upper),
    Predicate("alphabetic", _is_alphabetic),
    Predicate("alphanumeric", _is_alphanumeric),
    Predicate("punctuation", _is_punctuation),
    Predicate("graphic", _is_graphic),
    Predicate("printing", _is_printing),
    Predicate("horizontal_whitespace", _is_horizontal_whitespace),
    Predicate("whitespace", _is_whitespace),
    Predicate("control", _is_control),
]


def _c_array_bytes(data: bytes) -> str:
    return ", ".join(f"0x{b:02X}" for b in data)


def _ordering_name(a: bytes, b: bytes) -> str:
    if a < b:
        return "ordering::less"
    if a > b:
        return "ordering::greater"
    return "ordering::equal"


def _write_header(path: str, inputs: list[bytes]) -> None:
    lowers = [bytes(_to_lower_byte(b) for b in data) for data in inputs]
    uppers = [bytes(_to_upper_byte(b) for b in data) for data in inputs]
    folded = [bytes(_to_lower_byte(b) for b in data) for data in inputs]

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("// This file is generated by tests/gen_vectors.py. Do not edit by hand.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n\n")
        f.write("namespace ascii_test_vectors\n")
        f.write("{\n")
        f.write("enum class classification_id : unsigned char\n")
        f.write("{\n")
        for p in _PREDICATES:
            f.write(f"    {p.name},\n")
        f.write("};\n\n")

        f.write("enum class ordering : signed char\n")
        f.write("{\n")
        f.write("    less = -1,\n")
        f.write("    equal = 0,\n")
        f.write("    greater = 1,\n")
        f.write("};\n\n")

        f.write("struct blob\n")
        f.write("{\n")
        f.write("    unsigned char const* data;\n")
        f.write("    std::size_t size;\n")
        f.write("};\n\n")

        for i, data in enumerate(inputs):
            if not data:
                continue
            f.write(f"inline constexpr unsigned char input_{i}[] = {{{_c_array_bytes(data)}}};\n")
            f.write(f"inline constexpr unsigned char lower_{i}[] = {{{_c_array_bytes(lowers[i])}}};\n")
            f.write(f"inline constexpr unsigned char upper_{i}[] = {{{_c_array_bytes(uppers[i])}}};\n")
        f.write("\n")

        f.write("inline constexpr blob inputs[] = {\n")
        for i, data in enumerate(inputs):
            ptr_expr = "nullptr" if len(data) == 0 else f"input_{i}"
            size_expr = "0" if len(data) == 0 else f"sizeof(input_{i})"
            f.write(f"    {{{ptr_expr}, {size_expr}}},\n")
        f.write("};\n\n")

        f.write("inline constexpr blob lowers[] = {\n")
        for i, data in enumerate(inputs):
            ptr_expr = "nullptr" if len(data) == 0 else f"lower_{i}"
            size_expr = "0" if len(data) == 0 else f"sizeof(lower_{i})"
            f.write(f"    {{{ptr_expr}, {size_expr}}},\n")
        f.write("};\n\n")

        f.write("inline constexpr blob uppers[] = {\n")
        for i, data in enumerate(inputs):
            ptr_expr = "nullptr" if len(data) == 0 else f"upper_{i}"
            size_expr = "0" if len(data) == 0 else f"sizeof(upper_{i})"
            f.write(f"    {{{ptr_expr}, {size_expr}}},\n")
        f.write("};\n\n")

        f.write("struct find_vector\n")
        f.write("{\n")
        f.write("    classification_id id;\n")
        f.write("    std::size_t input_index;\n")
        f.write("    std::size_t first_invalid_index;\n")
        f.write("    std::size_t last_invalid_index;\n")
        f.write("};\n\n")

        f.write("inline constexpr find_vector find_vectors[] = {\n")
        for i, data in enumerate(inputs):
            for p in _PREDICATES:
                n = len(data)
                first = n
                last = n
                for j, b in enumerate(data):
                    if not p.fn(b):
                        first = j
                        break
                for j in range(n - 1, -1, -1):
                    if not p.fn(data[j]):
                        last = j
                        break
                f.write(f"    {{classification_id::{p.name}, {i}u, {first}u, {last}u}},\n")
        f.write("};\n\n")

        f.write("struct map_vector\n")
        f.write("{\n")
        f.write("    std::size_t input_index;\n")
        f.write("};\n\n")

        f.write("inline constexpr map_vector map_vectors[] = {\n")
        for i in range(len(inputs)):
            f.write(f"    {{{i}u}},\n")
        f.write("};\n\n")

        f.write("struct cmp_vector\n")
        f.write("{\n")
        f.write("    std::size_t lhs_index;\n")
        f.write("    std::size_t rhs_index;\n")
        f.write("    ordering expected;\n")
        f.write("};\n\n")

        f.write("inline constexpr cmp_vector compare_vectors[] = {\n")
        for i in range(len(inputs)):
            for j in range(len(inputs)):
                f.write(f"    {{{i}u, {j}u, {_ordering_name(folded[i], folded[j])}}},\n")
        f.write("};\n")

        f.write("} // namespace ascii_test_vectors\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--output", default="tests/generated_vectors.hpp")
    args = ap.parse_args()

    inputs = _generate_inputs(args.seed)
    _write_header(args.output, inputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
